load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "camera_3d",
    srcs = ["camera_3d.cpp"],
    hdrs = ["camera_3d.h"],
    deps = [
        "@glm",
    ],
)

cc_library(
    name = "camera_3d_sample",
    srcs = ["camera_3d_sample.cpp"],
    hdrs = ["camera_3d.h"],
    deps = [
        "@glm",
    ],
)
